# Generated by Django 2.1.5 on 2019-02-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_car_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_img',
        ),
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
