# Generated by Django 2.1.5 on 2019-02-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20190216_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_image',
            new_name='car_img',
        ),
    ]
